"""add voip token and outbound call intents

Revision ID: 5172338f2d41
Revises: 783df8b9e6c0
Create Date: 2026-02-25 13:00:31.907636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5172338f2d41'
down_revision: Union[str, None] = '783df8b9e6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbound_call_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('reminder_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ring_message', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('ringing_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('end_reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbound_call_intents_chat_id'), 'outbound_call_intents', ['chat_id'], unique=False)
    op.create_index(op.f('ix_outbound_call_intents_status'), 'outbound_call_intents', ['status'], unique=False)
    op.create_index(op.f('ix_outbound_call_intents_user_id'), 'outbound_call_intents', ['user_id'], unique=False)
    op.add_column('users', sa.Column('voip_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'voip_token')
    op.drop_index(op.f('ix_outbound_call_intents_user_id'), table_name='outbound_call_intents')
    op.drop_index(op.f('ix_outbound_call_intents_status'), table_name='outbound_call_intents')
    op.drop_index(op.f('ix_outbound_call_intents_chat_id'), table_name='outbound_call_intents')
    op.drop_table('outbound_call_intents')
    # ### end Alembic commands ###
