"""add voice_name to bots

Revision ID: 783df8b9e6c0
Revises: f72a37f75e9c
Create Date: 2026-02-25 12:04:57.473845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '783df8b9e6c0'
down_revision: Union[str, None] = 'f72a37f75e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('bots', sa.Column('voice_name', sa.String(length=50), nullable=False, server_default='Kore'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'voice_name')
    # ### end Alembic commands ###
